# 2022-12-02T08:00:00Z

	# The API end points.
	@baseUrl = https://opendata-download-metfcst.smhi.se/api/category/pmp3g/version/2

###
{{baseUrl}}/approvedtime.json

###
{{baseUrl}}/geotype/multipoint/validtime.json

###
{{baseUrl}}/parameter.json

###
{{baseUrl}}/geotype/multipoint.json

###
{{baseUrl}}/geotype/multipoint/
validtime/2022-12-01T20:00:00Z/
parameter/{parameter}/
leveltype/{leveltype}/
level/{level}
/data.json
?with-geo=false

###

# {{baseUrl}}/geotype/point/lon/16/lat/58/data.json
{{baseUrl}}/geotype/point/lon/16/lat/58/data.json

###
{{baseUrl}}/geotype/multipoint/validtime/20221201T160000Z/parameter/t/leveltype/hl/level/2/data.json?with-geo=false

# {{baseUrl}}/geotype/multipoint/
# validtime/{validtime}/
# parameter/{parameter}/
# leveltype/{leveltype}/
# level/{level}
# /data.json
# ?with-geo=false